---
- name: Create yum repo directory
  ansible.builtin.file:
    path: /etc/yum.repos.d
    state: directory
    mode: 0755

- name: Add Fluentbit key
  ansible.builtin.template:
    src: yum.conf.j2
    dest: /etc/yum.repos.d/fluent-bit.repo
    mode: 0755

- name: Comment out rsyslog time format
  replace:
    dest: /etc/rsyslog.conf
    regexp: '^\$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
    replace: '#$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
  notify: Restart syslog

- name: Install fluent-bit
  ansible.builtin.yum:
    name: "{{ fluentbit_pkg_name }}-{{ fluentbit_pkg_version }}"
    state: present

- name: Enable Fluentbit service
  ansible.builtin.systemd:
    name: "{{ fluentbit_svc_name }}"
    enabled: true
    daemon_reload: true
  tags: notest

- name: Create main Fluentbit configuration.
  ansible.builtin.template:
    src: ./templates/fluent-bit.conf.j2
    dest: "{{ fluentbit_conf_file_path }}"
    mode: 0644
  notify: Restart Fluentbit

- name: Create Fluentbit parser configuration
  ansible.builtin.template:
    src: ./templates/fluent-bit-parsers.conf.j2
    dest: "{{ fluentbit_svc_parsers_file }}"
    mode: 0644
  notify: Restart Fluentbit

# - name: Copy database file
#   ansible.builtin.copy:
#     src: ./files/GeoLite2-City_20231010.tar.gz
#     dest: "{{ fluentbit_conf_directory }}"
#     mode: 0644

- name: Extract database file
  ansible.builtin.unarchive:
    src: "./files/GeoLite2-City_20231010.tar.gz"
    dest: "{{ fluentbit_conf_directory }}"

- name: Create lua directory
  ansible.builtin.file:
    path: "{{ fluentbit_conf_directory }}/{{ fluentbit_lua_conf_file_path }}"
    state: directory
    mode: 0755

- name: Add Lua files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ fluentbit_conf_directory }}/{{ fluentbit_lua_conf_file_path }}/{{ item.name }}"
    mode: 0644
  with_items:
    - {src: ./templates/modify_date.lua.j2, name: modify_date.lua}
    - {src: ./templates/add_fields.lua.j2, name: add_fields.lua}
    - {src: ./templates/add_request_pattern.lua.j2, name: add_request_pattern.lua}
  notify: Restart Fluentbit

- name: Create service.d directory
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d"
    state: directory
    mode: 0755
  when: fluentbit_svc_limit_open_files is defined

- name: Override systemd configuration if needed
  ansible.builtin.template:
    src: fluent-bit-override.conf.j2
    dest: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d/override.conf"
    mode: 0644
  when: fluentbit_svc_limit_open_files is defined

- name: Delete override systemd configuration if needed
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d/override.conf"
    state: absent
  when: fluentbit_svc_limit_open_files is not defined
